# Generated by Django 5.1.2 on 2024-11-05 06:25

from django.db import migrations

def create_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('users', 'Profile')
    
    # Create profile for each existing user
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user)

def remove_profiles(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    Profile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_profiles, remove_profiles),
    ]
